volumes:
  mongo_data:
services:
  api-fastapi:
    restart: always
    build:
      context: ./api-base-fastapi
      dockerfile: Dockerfile
    volumes:
      - /tmp:/tmp
    ports: 
      - "8080:8080"
    depends_on:
      - mongodb
      - kafka

  api-github:
    build:
      context: ./api-github
      dockerfile: Dockerfile
    volumes:
      - /tmp:/tmp
    ports:
      - "7000:7000"
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "8001:8001"
    command: ["mongod", "--port", "8001"]

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 8001
      ME_CONFIG_BASICAUTH: false
      
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "LISTENER_LOCAL://127.0.0.1:9092,LISTENER_DOCKER://kafka:9093"
      KAFKA_ADVERTISED_LISTENERS: "LISTENER_LOCAL://127.0.0.1:9092,LISTENER_DOCKER://kafka:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "LISTENER_LOCAL:PLAINTEXT,LISTENER_DOCKER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "LISTENER_DOCKER"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

