volumes:
  mongo_data:
services:
  api-fastapi:
    build:
      context: ./api-base-fastapi
      dockerfile: Dockerfile
    volumes:
      - /tmp:/tmp
    ports: 
      - "8000:8000"
    #depends-on:
    # - mongo
  api-github:
    build:
      context: ./api-github
      dockerfile: Dockerfile
    volumes:
      - /tmp:/tmp
    ports:
      - "7000:7000"
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "8001:8001"
    command: ["mongod", "--port", "8001"]

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 8001
      ME_CONFIG_BASICAUTH: false
  kafka:
    image: apache/kafka:latest
    restart: always
    ports:
      - "8082:8082"
  mlflow:
    image: bitnami/mlflow:latest
    restart: always
    ports:
      - "8083:8083"
