name: Build and Deploy API Request Github

on:
  push:
    branches: ["main"]
    paths:
      - 'api-base-mongo/**'
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: "AzureContainerRegistryMLopsMPT"
  RESOURCE_GROUP: "Projet_M2_MLOPS_MRO_PEN_TAN"
  CLUSTER_NAME: "canada-central"

jobs:
  buildAndDeployMongoApi:
    if: contains(github.event.head_commit.modified, 'api-base-mongo/')
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v4

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_URL }}  # Votre ACR
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}


      # Builds and pushes an image up to your Azure Container Registry
      - name: Build Docker image
        run: docker build -t ${{ secrets.AZURE_REGISTRY_URL }}/api-base-mongo:latest ./api-base-mongo
      
      - name: Versioning
        run: |
          VERSION_FILE=./api-base-mongo/version.txt
          if [ ! -f "$VERSION_FILE" ]; then
            echo "0" > $VERSION_FILE
          fi
          VERSION=$(cat $VERSION_FILE)
          NEW_VERSION=VERSION+1
          echo "$NEW_VERSION" > $VERSION_FILE
      
      - name: Push Docker image
        run: docker push ${{ secrets.AZURE_REGISTRY_URL }}/api-base-mongo:latest
